from enum import StrEnum


class FeedbackReason(StrEnum):
    INCORRECT = "INCORRECT"
    INCOMPLETE = "INCOMPLETE"
    HALLUCINATION = "HALLUCINATION"
    NOT_RELEVANT = "NOT_RELEVANT"
    POOR_EXPLANATION = "POOR_EXPLANATION"
    OUTDATED = "OUTDATED"
    OTHER = "OTHER"