from enum import StrEnum


class GatewayErrorCode(StrEnum):

    UNKNOWN_ERROR = "UNKNOWN_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"

    REQUEST_TIMEOUT = "REQUEST_TIMEOUT"
    SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"

    AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED"
    AUTHORIZATION_FAILED = "AUTHORIZATION_FAILED"

    # Portfolio
    PORTFOLIO_NOT_FOUND = "PORTFOLIO_NOT_FOUND"

    # Scheme
    SCHEME_NOT_FOUND = "SCHEME_NOT_FOUND"
    SCHEME_SEARCH_FAILED = "SCHEME_SEARCH_FAILED"
    SCHEME_DETAILS_NOT_FOUND = "SCHEME_DETAILS_NOT_FOUND"

    # Customer
    CUSTOMER_NOT_FOUND = "CUSTOMER_NOT_FOUND"
    