[project]
name = "project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.136.1",
    "numpy>=2.4.6",
    "pandas>=3.0.3",
    "pgvector>=0.4.2",
    "psycopg2-binary>=2.9.12",
    "pymupdf>=1.27.2.3",
    "requests==2.31.0",
    "sentence-transformers>=5.5.1",
]
[tools.fastapi]
entrypoint = "main.app"
