from enum import StrEnum

class InsightCode(StrEnum):
    GOOD_PERFORMANCE = "GOOD_PERFORMANCE"
    LOW_PERFORMANCE = "LOW_PERFORMANCE"
    GOOD_DIVERSIFICATION = "GOOD_DIVERSIFICATION"
    LOW_DIVERSIFICATION = "LOW_DIVERSIFICATION"
    HIGH_PORTFOLIO_RISK = "HIGH_PORTFOLIO_RISK"
    HIGH_RISK_CONTRIBUTOR = "HIGH_RISK_CONTRIBUTOR"
    GOOD_HEALTH = "GOOD_HEALTH"
    LOW_HEALTH = "LOW_HEALTH"

    GOAL_ON_TRACK = 'GOAL_ON_TRACK'
    GOAL_AT_RISK = "GOAL_AT_RISK"
    GOAL_OFF_TRACK = "GOAL_OFF_TRACK"
    GOAL_FUTURE_AMOUNT = "GOAL_FUTURE_AMOUNT"
    GOAL_PROJECTED_CORPUS = "GOAL_PROJECTED_CORPUS"
    GOAL_FUNDING_GAP = "GOAL_FUNDING_GAP"