from enum import StrEnum

class InsightCode(StrEnum):
    GOOD_PERFORMANCE = "GOOD_PERFORMANCE"
    LOW_PERFORMANCE = "LOW_PERFORMANCE"
    GOOD_DIVERSIFICATION = "GOOD_DIVERSIFICATION"
    LOW_DIVERSIFICATION = "LOW_DIVERSIFICATION"
    HIGH_PORTFOLIO_RISK = "HIGH_PORTFOLIO_RISK"
    HIGH_RISK_CONTRIBUTOR = "HIGH_RISK_CONTRIBUTOR"
    GOOD_HEALTH = "GOOD_HEALTH"
    LOW_HEALTH = "LOW_HEALTH"