"""feedback_issue_id column added in feedback table

Revision ID: 2a76b8be0dc6
Revises: 8622b661d743
Create Date: 2026-07-23 14:53:22.711290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a76b8be0dc6'
down_revision: Union[str, Sequence[str], None] = '8622b661d743'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('feedback_issue_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'feedback', 'feedback_issues', ['feedback_issue_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_feedback_issue_id'), table_name='feedback')
    op.drop_column('feedback', 'feedback_issue_id')
