"""renamed metadata to _metadata

Revision ID: 5e76ef8cef0b
Revises: 958dfa94874a
Create Date: 2026-07-22 19:30:57.394056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e76ef8cef0b'
down_revision: Union[str, Sequence[str], None] = '958dfa94874a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('trace_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='evaluationstatus'), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('trigger_type', sa.Enum('FEEDBACK', 'CRON', 'MANUAL', name='evaluationtriggertype'), nullable=False),
    sa.Column('evaluator_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluations_conversation_id'), 'evaluations', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_evaluations_message_id'), 'evaluations', ['message_id'], unique=True)
    op.create_index(op.f('ix_evaluations_trace_id'), 'evaluations', ['trace_id'], unique=False)
    op.create_table('evaluation_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evaluation_id', sa.UUID(), nullable=False),
    sa.Column('metric', sa.Enum('LATENCY', 'TOKEN_USAGE', 'RESPONSE_VALIDATION', 'FAITHFULNESS', 'ANSWER_CORRECTNESS', 'HALLUCINATION', 'ANSWER_RELEVANCY', 'PLANNER_ACCURACY', 'TOOL_ACCURACY', 'HITL', 'MCP', 'COST', 'PLANNER_INTENT', 'PLANNER_CAPABILITY', 'PLANNER_TOOL_SELECTION', 'PLANNER_CONFIDENCE', 'PLANNER_REASONING', 'PROMPT_SYSTEM', 'PROMPT_USER', 'PROMPT_CONTEXT', 'PROMPT_COMPLIANCE', 'PROMPT_LENGTH', 'PROMPT_HISTORY', 'CONTEXTUAL_RELEVANCY', 'CONTEXTUAL_PRECISION', 'CONTEXTUAL_RECALL', 'TOXICITY', 'BIAS', name='metrictype'), nullable=False),
    sa.Column('source', sa.Enum('RULE', 'DEEPEVAL', 'CUSTOM', 'TRACE', 'LLM_JUDGE', name='metricsource'), nullable=False),
    sa.Column('status', sa.Enum('PASSED', 'FAILED', 'SKIPPED', name='metricstatus'), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_metrics_evaluation_id'), 'evaluation_metrics', ['evaluation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evaluation_metrics_evaluation_id'), table_name='evaluation_metrics')
    op.drop_table('evaluation_metrics')
    op.drop_index(op.f('ix_evaluations_trace_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_message_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_conversation_id'), table_name='evaluations')
    op.drop_table('evaluations')
    # ### end Alembic commands ###
