"""feedback issue and occurence tables are created

Revision ID: 7fad0933b290
Revises: 18bda9182da8
Create Date: 2026-07-23 13:58:25.679474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7fad0933b290'
down_revision: Union[str, Sequence[str], None] = '18bda9182da8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback_issues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('component', sa.String(length=100), nullable=False),
    sa.Column('category', sa.Enum('PLANNER', 'RETRIEVAL', 'PROMPT', 'BUSINESS', 'KNOWLEDGE', 'OTHER', name='issuecategory'), nullable=False),
    sa.Column('root_cause', sa.Enum('PLANNER_PORTFOLIO_IGNORED', 'PLANNER_RISK_PROFILE_IGNORED', 'PLANNER_GOAL_IGNORED', 'RETRIEVAL_NO_CONTEXT', 'PROMPT_GENERIC_RESPONSE', 'BUSINESS_INCORRECT_RECOMMENDATION', 'UNKNOWN', name='rootcause'), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='notificationseverity'), nullable=False),
    sa.Column('jira_key', sa.String(length=50), nullable=True),
    sa.Column('jira_url', sa.String(length=100), nullable=True),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='feedbackissuestatus'), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_issues_category'), 'feedback_issues', ['category'], unique=False)
    op.create_index(op.f('ix_feedback_issues_component'), 'feedback_issues', ['component'], unique=False)
    op.create_index(op.f('ix_feedback_issues_root_cause'), 'feedback_issues', ['root_cause'], unique=False)
    op.create_index(op.f('ix_feedback_issues_status'), 'feedback_issues', ['status'], unique=False)
    op.create_table('feedback_occurrences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('issue_id', sa.UUID(), nullable=False),
    sa.Column('feedback_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['issue_id'], ['feedback_issues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_occurrences_conversation_id'), 'feedback_occurrences', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_feedback_occurrences_issue_id'), 'feedback_occurrences', ['issue_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_occurrences_issue_id'), table_name='feedback_occurrences')
    op.drop_index(op.f('ix_feedback_occurrences_conversation_id'), table_name='feedback_occurrences')
    op.drop_table('feedback_occurrences')
    op.drop_index(op.f('ix_feedback_issues_status'), table_name='feedback_issues')
    op.drop_index(op.f('ix_feedback_issues_root_cause'), table_name='feedback_issues')
    op.drop_index(op.f('ix_feedback_issues_component'), table_name='feedback_issues')
    op.drop_index(op.f('ix_feedback_issues_category'), table_name='feedback_issues')
    op.drop_table('feedback_issues')
    # ### end Alembic commands ###
