"""Removed component column from feedback_issue table

Revision ID: 8622b661d743
Revises: 7fad0933b290
Create Date: 2026-07-23 14:40:15.887768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8622b661d743'
down_revision: Union[str, Sequence[str], None] = '7fad0933b290'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback_issues', 'component')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback_issues', sa.Column('component', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
