"""create feedback table

Revision ID: 958dfa94874a
Revises: ed1a9589bf1d
Create Date: 2026-07-20 04:17:45.159943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '958dfa94874a'
down_revision: Union[str, Sequence[str], None] = 'ed1a9589bf1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.String(length=12), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('trace_id', sa.UUID(), nullable=True),
    sa.Column('signal', postgresql.ENUM('POSITIVE', 'NEGATIVE', name='feedback_signal'), nullable=False),
    sa.Column('reason', postgresql.ENUM('INCORRECT', 'INCOMPLETE', 'HALLUCINATION', 'NOT_RELEVANT', 'POOR_EXPLANATION', 'OUTDATED', 'OTHER', name='feedback_reason'), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    # ### end Alembic commands ###
