"""Add two columns to message table

Revision ID: b14daccd1699
Revises: 3119252b5a3a
Create Date: 2026-07-15 12:38:03.025181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b14daccd1699'
down_revision: Union[str, Sequence[str], None] = '3119252b5a3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

message_type = sa.Enum(
    "TEXT",
    "TOOL",
    "INTERRUPT",
    "RESUME",
    "SUMMARY",
    "TITLE",
    "EVENT",
    name="messagetype",
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    message_type.create(op.get_bind(), checkfirst=True)
    op.add_column('messages', sa.Column('trace_id', sa.String(length=64), nullable=True))
    op.add_column('messages', sa.Column('message_type', message_type, nullable=False, server_default="TEXT"))
    op.create_index(op.f('ix_messages_trace_id'), 'messages', ['trace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_trace_id'), table_name='messages')
    op.drop_column('messages', 'message_type')
    op.drop_column('messages', 'trace_id')