"""Conversation summary table created

Revision ID: ed1a9589bf1d
Revises: b14daccd1699
Create Date: 2026-07-15 15:09:39.811427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed1a9589bf1d'
down_revision: Union[str, Sequence[str], None] = 'b14daccd1699'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('start_sequence', sa.Integer(), nullable=False),
    sa.Column('end_sequence', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'version', name='uq_conversation_summary_version')
    )
    op.create_index('idx_conversation_summary_sequence', 'conversation_summaries', ['conversation_id', 'end_sequence'], unique=False)
    op.create_index(op.f('ix_conversation_summaries_conversation_id'), 'conversation_summaries', ['conversation_id'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_summaries_conversation_id'), table_name='conversation_summaries')
    op.drop_index('idx_conversation_summary_sequence', table_name='conversation_summaries')
    op.drop_table('conversation_summaries')
    # ### end Alembic commands ###
