"""update the column in the Document table

Revision ID: fd8c59f49b31
Revises: 0bb8ced31fb1
Create Date: 2026-06-15 12:45:24.146945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fd8c59f49b31'
down_revision: Union[str, Sequence[str], None] = '0bb8ced31fb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('amc_name', sa.String(length=100), nullable=False))
    op.drop_column('documents', 'fund_house')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('fund_house', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('documents', 'amc_name')
     # ### end Alembic commands ###
