"""make the workflow column as nullable in conversation table

Revision ID: ff405123c9a6
Revises: 2a76b8be0dc6
Create Date: 2026-08-07 12:25:48.512105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff405123c9a6'
down_revision: Union[str, Sequence[str], None] = '2a76b8be0dc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversations', 'workflow',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index(op.f('ix_conversations_workflow'), table_name='conversations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_conversations_workflow'), 'conversations', ['workflow'], unique=False)
    op.alter_column('conversations', 'workflow',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
